version: "3.8"

services:
  create-service:
    build: ./app/domain/create
    ports:
      - "8001:8001"
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/tables_db

  read-service:
    build: ./app/domain/read
    ports:
      - "8002:8002"
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/tables_db

  update-service:
    build: ./app/domain/update
    ports:
      - "8003:8003"
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/tables_db

  delete-service:
    build: ./app/domain/delete
    ports:
      - "8004:8004"
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=mysql+pymysql://user:password@db/tables_db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: tables_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
