version: '3.8'

services:
  tables-db:
    image: mysql:8.0
    container_name: tables-db
    restart: always
    environment:
      MYSQL_DATABASE: tables_management
      MYSQL_USER: tables_admin
      MYSQL_PASSWORD: mysql000
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  tables-create:
    build:
      context: .
      dockerfile: app/domain/create/Dockerfile
      volumes:
      - .:/app
    ports:
      - "8001:8001"
    depends_on:
      - tables-db
    restart: always

  tables-read:
    build:
      context: .
      dockerfile: app/domain/read/Dockerfile
      volumes:
      - .:/app
    ports:
      - "8002:8002"
    depends_on:
      - tables-db
    restart: always

  tables-update:
    build:
      context: .
      dockerfile: app/domain/update/Dockerfile
      volumes:
      - .:/app
    ports:
      - "8003:8003"
    depends_on:
      - tables-db
    restart: always

  tables-delete:
    build:
      context: .
      dockerfile: app/domain/delete/Dockerfile
      volumes:
      - .:/app
    ports:
      - "8004:8004"
    depends_on:
      - tables-db
    restart: always

volumes:
  db_data:
