version: '3.8'

services:
  reservation-db:
    image: postgres:latest
    container_name: reservation-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  reservation-create:
    build:
      context: .
      dockerfile: src/business/create/Dockerfile
    ports:
      - "3100:3100"
    env_file:
      - .env
    depends_on:
      - reservation-db
    restart: always

  reservation-read:
    build:
      context: .
      dockerfile: src/business/read/Dockerfile
    ports:
      - "3101:3101"
    env_file:
      - .env
    depends_on:
      - reservation-db
    restart: always

  reservation-update:
    build:
      context: .
      dockerfile: src/business/update/Dockerfile
    ports:
      - "3102:3102"
    env_file:
      - .env
    depends_on:
      - reservation-db
    restart: always

  reservation-delete:
    build:
      context: .
      dockerfile: src/business/delete/Dockerfile
    ports:
      - "3103:3103"
    env_file:
      - .env
    depends_on:
      - reservation-db
    restart: always

volumes:
  db_data:
