version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: admin123.4a
      MYSQL_DATABASE: configurations
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin123.4a
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  config-crud-create:
    build: ./config-crud-create
    depends_on:
      - mysql
    environment:
      - DB_HOST=config-service.cffsasur76pg.us-east-1.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASSWORD=admin123.4a
      - DB_NAME=configurations
      - DB_PORT=3306
    ports:
      - "8001:8001"

  config-crud-read:
    build: ./config-crud-read
    depends_on:
      - mysql
    environment:
      - DB_HOST=config-service.cffsasur76pg.us-east-1.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASSWORD=admin123.4a
      - DB_NAME=configurations
      - DB_PORT=3306
    ports:
      - "8002:8002"

  config-crud-update:
    build: ./config-crud-update
    depends_on:
      - mysql
    environment:
      - DB_HOST=config-service.cffsasur76pg.us-east-1.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASSWORD=admin123.4a
      - DB_NAME=configurations
      - DB_PORT=3306
    ports:
      - "8003:8003"

  config-crud-delete:
    build: ./config-crud-delete
    depends_on:
      - mysql
    environment:
      - DB_HOST=config-service.cffsasur76pg.us-east-1.rds.amazonaws.com
      - DB_USER=admin
      - DB_PASSWORD=admin123.4a
      - DB_NAME=configurations
      - DB_PORT=3306
    ports:
      - "8004:8004"

volumes:
  mysql_data:
