version: '3.8'

services:
  restaurants-db:
    image: mariadb:latest
    container_name: restaurants-db
    restart: always
    environment:
      MYSQL_DATABASE: restaurants_db
      MYSQL_USER: res_admin
      MYSQL_PASSWORD: maria111
      MYSQL_ROOT_PASSWORD: rootpassword
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  restaurants-create:
    build:
      context: .
      dockerfile: app/domain/create/Dockerfile
    ports:
      - "5001:5001"
    depends_on:
      - restaurants-db
    restart: always

  restaurants-read:
    build:
      context: .
      dockerfile: app/domain/read/Dockerfile
    ports:
      - "5002:5002"
    depends_on:
      - restaurants-db
    restart: always

  restaurants-update:
    build:
      context: .
      dockerfile: app/domain/update/Dockerfile
    ports:
      - "5003:5003"
    depends_on:
      - restaurants-db
    restart: always

  restaurants-delete:
    build:
      context: .
      dockerfile: app/domain/delete/Dockerfile
    ports:
      - "5004:5004"
    depends_on:
      - restaurants-db
    restart: always

volumes:
  db_data:
