version: '3.8'

services:
  authentication-create:
    build:
      context: ./src/business/create
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always

  authentication-read:
    build:
      context: ./src/business/read
    ports:
      - "3001:3000"
    env_file:
      - .env
    restart: always

  authentication-update:
    build:
      context: ./src/business/update
    ports:
      - "3002:3000"
    env_file:
      - .env
    restart: always

  authentication-delete:
    build:
      context: ./src/business/delete
    ports:
      - "3003:3000"
    env_file:
      - .env
    restart: always

  authentication-login:
    build:
      context: ./src/business/login
    ports:
      - "3004:3000"
    env_file:
      - .env
    restart: always
