version: '3.8'

services:
  authentication-create:
    build:
      context: .
      dockerfile: src/business/create/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always

  authentication-read:
    build:
      context: .
      dockerfile: src/business/read/Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    restart: always

  authentication-update:
    build:
      context: .
      dockerfile: src/business/update/Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - .env
    restart: always

  authentication-delete:
    build:
      context: .
      dockerfile: src/business/delete/Dockerfile
    ports:
      - "3003:3000"
    env_file:
      - .env
    restart: always

  authentication-login:
    build:
      context: .
      dockerfile: src/business/login/Dockerfile
    ports:
      - "3004:3000"
    env_file:
      - .env
    restart: always
