version: '3.8'

services:
  authentication-db:
    image: postgres:latest
    container_name: authentication-db
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  authentication-create:
    build:
      context: .
      dockerfile: src/business/create/Dockerfile
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - authentication-db
    restart: always

  authentication-read:
    build:
      context: .
      dockerfile: src/business/read/Dockerfile
    ports:
      - "3001:3000"
    env_file:
      - .env
    depends_on:
      - authentication-db
    restart: always

  authentication-update:
    build:
      context: .
      dockerfile: src/business/update/Dockerfile
    ports:
      - "3002:3000"
    env_file:
      - .env
    depends_on:
      - authentication-db
    restart: always

  authentication-delete:
    build:
      context: .
      dockerfile: src/business/delete/Dockerfile
    ports:
      - "3003:3000"
    env_file:
      - .env
    depends_on:
      - authentication-db
    restart: always

  authentication-login:
    build:
      context: .
      dockerfile: src/business/login/Dockerfile
    ports:
      - "3004:3000"
    env_file:
      - .env
    depends_on:
      - authentication-db
    restart: always

volumes:
  db_data:
