version: '3.8'

services:
  authentication-service:
    build:
      context: . 
    ports:
      - "3000:3000" 
    env_file:
      - .env 
    depends_on:
      - db 
    networks:
      - app-network

  db:
    image: postgres:14 
    container_name: postgres_db
    restart: always 
    environment:
      POSTGRES_USER: ${DB_USER} 
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432" 
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data:
